---

version: "3.9"

services:
  
  traefik:
    image: traefik:latest
    volumes:
      - "/home/admin/identidock/traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "/home/admin/identidock/traefik/conf.d/dynamic_conf.yml:/etc/traefik/conf.d/dynamic_conf.yml:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - proxy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager 
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
  
  nginx:
    
    image: spider2111/proxy:0.1
    environment:
      - NGINX_PROXY=http://identidock:9090
      - NGINX_HOST=172.17.88.139
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - proxy
      - backend
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: curl -sS http://127.0.0.1:4004/ptm/api/healthcheck || echo 1
      interval: 30s
      timeout: 3s
      retries: 12
      
#      placement:
#        constraints:
#          - node.role == manager 

  identidock:
    image: spider2111/identidock-feature:test
    networks:
      - backend
    environment:
      - ENV=PROD
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager 
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: curl -sS http://127.0.0.1:4004/ptm/api/healthcheck || echo 1
      interval: 30s
      timeout: 3s
      retries: 12  
  #    placement:
  #      constraints:
  #        - node.role == manager 

  dnmonster:
    image: amouat/dnmonster:1.0
    networks:
      - backend
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == manager 
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: curl -sS http://127.0.0.1:4004/ptm/api/healthcheck || echo 1
      interval: 30s
      timeout: 3s
      retries: 12

   #   placement:
   #     constraints:
   #       - node.role == manager 
  
  redis:
    image: redis:3.0
    networks:
      - backend
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager 
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: curl -sS http://127.0.0.1:4004/ptm/api/healthcheck || echo 1
      interval: 30s
      timeout: 3s
      retries: 12

  
  drill:
    image: spider2111/alpine:driller
    networks:
      - backend
    command: ["sleep", "1000000000"]
    deploy:
      replicas: 2

   #   placement:
   #     constraints:
   #       - node.role == manager 
networks:
  proxy:
    external: true
  backend:
    external: false 