version: "3.5"
services:
  proxy:
    image: sider2111/proxy:0.1
    ports:
      - "80:80"
    links:
      - "identidock"
    environment:
      - NGINX_HOST=172.17.88.167
      - NGINX_PROXY=http://identidock:9090
  identidock:
    build: .
    ports: 
      - "9090:9090"
    environment:
      ENV: PROD
    volumes:
      - ./app:/app
    links:
      - "dnmonster"
      - "redis"
  
  dnmonster:
    image: amouat/dnmonster:1.0
  
  redis:
    image: redis:3.0
